# Primera etapa: 
descarga y limpieza de los datos

In [64]:
#1 Definimos la función para obtener la gravedad local
def obtener_gravedad_local(latitud: float, longitud: float, api_key: str) -> dict:
    url = 'https://gravity.amentum.io/egm2008/gravity_anomaly'

    # Cambiamos las etiquetas a nombres completos
    params = {
        "latitude": latitud,   # Antes era "lat"
        "longitude": longitud  # Antes era "lon"
    }

    headers = {
        "API-Key": api_key,
        "accept": "application/json"
    }

    import requests
    response = requests.get(url, headers=headers, params=params)

    if response.status_code == 200:
        return response.json()
    else:
        return {"error": f"Fallo {response.status_code}", "detalle": response.text}

Eligimos 5 puntos del planeta para compara e

In [65]:
puntos_interes = [
    {"nombre": "Monte Everest", "lat": 27.98, "lon": 86.92},
    {"nombre": "Fosa de las Marianas", "lat": 11.37, "lon": 142.59},
    {"nombre": "Ciudad de México", "lat": 19.43, "lon": -99.13},
    {"nombre": "Castellón de la Plana", "lat": 39.9860, "lon": -0.0513},
    {"nombre": " Cuenca de Tanezrouft", "lat":22.251, "lon": -2.246}
]

In [66]:
# Definimos el punto de interés
cdmx = {"nombre": "Monte Everest", "lat": 27.9880, "lon": 86.9250}

# Realizamos la petición (usando la función que armamos antes)
datos_cdmx = obtener_gravedad_local(cdmx['lat'], cdmx['lon'], 'FvryxkZBiRpgWutoujRUWcHKkj4z35qu')


print("Respuesta de la API:", datos_cdmx)

# Solo si la respuesta tiene lo que buscamos, lo imprimimos
if 'gravity_anomaly' in datos_cdmx:
    print(f"Anomalía en CDMX: {datos_cdmx['gravity_anomaly']} mGal")
else:
    print("Error: La API no devolvió la anomalía. Revisa el mensaje de arriba.")

Respuesta de la API: {'eta': {'units': 'arcsec', 'value': -2.481171931342914}, 'gravity_anomaly': {'units': 'mGal', 'value': 663.1848550445642}, 'xi': {'units': 'arcsec', 'value': -29.173576028918923}}
Anomalía en CDMX: {'units': 'mGal', 'value': 663.1848550445642} mGal

In [67]:
# Definimos el punto de interés
cdmx = {"nombre": "Fosa de las Marianas", "lat": 11.37, "lon": 142.59}

# Realizamos la petición (usando la función que armamos antes)
datos_cdmx = obtener_gravedad_local(cdmx['lat'], cdmx['lon'], 'FvryxkZBiRpgWutoujRUWcHKkj4z35qu')

print("Respuesta de la API:", datos_cdmx)

# Solo si la respuesta tiene lo que buscamos, lo imprimimos
if 'gravity_anomaly' in datos_cdmx:
    print(f"Anomalía en CDMX: {datos_cdmx['gravity_anomaly']} mGal")
else:
    print("Error: La API no devolvió la anomalía. Revisa el mensaje de arriba.")

Respuesta de la API: {'eta': {'units': 'arcsec', 'value': -8.133320480866733}, 'gravity_anomaly': {'units': 'mGal', 'value': -318.5888344761341}, 'xi': {'units': 'arcsec', 'value': -1.784552691471896}}
Anomalía en CDMX: {'units': 'mGal', 'value': -318.5888344761341} mGal

In [68]:
# Definimos el punto de interés
cdmx = {"nombre": "Ciudad de México", "lat": 19.4326, "lon": -99.1332}

# Realizamos la petición (usando la función que armamos antes)
datos_cdmx = obtener_gravedad_local(cdmx['lat'], cdmx['lon'], 'FvryxkZBiRpgWutoujRUWcHKkj4z35qu')

print("Respuesta de la API:", datos_cdmx)

#  Solo si la respuesta tiene lo que buscamos, lo imprimimos
if 'gravity_anomaly' in datos_cdmx:
    print(f"Anomalía en CDMX: {datos_cdmx['gravity_anomaly']} mGal")
else:
    print("Error: La API no devolvió la anomalía. Revisa el mensaje de arriba.")

Respuesta de la API: {'eta': {'units': 'arcsec', 'value': -1.2853022741183195}, 'gravity_anomaly': {'units': 'mGal', 'value': 33.574860133823094}, 'xi': {'units': 'arcsec', 'value': 1.132915669389644}}
Anomalía en CDMX: {'units': 'mGal', 'value': 33.574860133823094} mGal

In [69]:
# Definimos el punto de interés
cdmx = {"nombre": "Castellón de la Plana", "lat": 39.9860, "lon": -0.0513}

print("Respuesta de la API:", datos_cdmx)

#  Solo si la respuesta tiene lo que buscamos, lo imprimimos
if 'gravity_anomaly' in datos_cdmx:
    print(f"Anomalía en CDMX: {datos_cdmx['gravity_anomaly']} mGal")
else:
    print("Error: La API no devolvió la anomalía. Revisa el mensaje de arriba.")

Respuesta de la API: {'eta': {'units': 'arcsec', 'value': -1.2853022741183195}, 'gravity_anomaly': {'units': 'mGal', 'value': 33.574860133823094}, 'xi': {'units': 'arcsec', 'value': 1.132915669389644}}
Anomalía en CDMX: {'units': 'mGal', 'value': 33.574860133823094} mGal

In [70]:
# Definimos el punto de interés
cdmx = {"nombre": "Cuenca de Tanezrouft", "lat": 22.251, "lon": -2.246} 

# Realizamos la petición (usando la función que armamos antes)
datos_cdmx = obtener_gravedad_local(cdmx['lat'], cdmx['lon'], 'FvryxkZBiRpgWutoujRUWcHKkj4z35qu')

print("Respuesta de la API:", datos_cdmx)

# Solo si la respuesta tiene lo que buscamos, lo imprimimos
if 'gravity_anomaly' in datos_cdmx:
    print(f"Anomalía en CDMX: {datos_cdmx['gravity_anomaly']} mGal")
else:
    print("Error: La API no devolvió la anomalía. Revisa el mensaje de arriba.")

Respuesta de la API: {'eta': {'units': 'arcsec', 'value': -3.2824460401726947}, 'gravity_anomaly': {'units': 'mGal', 'value': -11.470237259214926}, 'xi': {'units': 'arcsec', 'value': 0.8477966093991907}}
Anomalía en CDMX: {'units': 'mGal', 'value': -11.470237259214926} mGal

In [71]:
import pandas as pd

# Al estar en la misma carpeta, solo necesitamos el nombre
path_local = "asteroids_data.csv"

try:
    # Cargamos directamente el archivo local
    # Recuerda mantener sep=';' si ese es el formato de tu archivo
    df = pd.read_csv(path_local, sep=';')
    
    # Aplicamos tus mejoras de estilo
    pd.set_option('display.max_columns', None)
    
    print("¡Archivo local cargado con éxito!")
    print(df.head())
    
except FileNotFoundError:
    print("Error: No encontré el archivo. Asegúrate de haberlo subido al entorno.")

¡Archivo local cargado con éxito!
                                                   id,neo_id,name,short_name,designation,nasa_url,magnitude,potentially_hazardous,close_approach_data,sentry,api_url,diameter_min_m,diameter_max_m,orbit_id,orbit_determination_date,first_observation_date,last_observation_date,data_arc_days,observations_used,orbit_uncertainty,min_orbit_intersection,jupiter_tisserand,epoch,eccentricity,semi_major_axis,inclination,ascending_node_longitude,orbital_period,perihelion_distance,perihelion_argument,aphelion_distance,perihelion_time,mean_anomaly,mean_motion,equinox,orbit_class_type,orbit_class_desc,orbit_class_range,sentry_data
2001620,2001620,1620 Geographos (1951 RA),Geogr...                         q (perihelion) < 1.017 AU,
2001863,2001863,1863 Antinous (1948 EA),Antinou...                         q (perihelion) < 1.017 AU,
2001915,2001915,1915 Quetzalcoatl (1953 EA),Que...                                                NaN
2001917,2001917,1917 Cuyo (1968 AA),Cuyo,1917,h...                                                NaN
2002063,2002063,2063 Bacchus (1977 HB),Bacchus,...                         q (perihelion) < 1.017 AU,

In [72]:
import pandas as pd

# 1. Cargamos el archivo asegurando que el separador sea la coma
# Si lo subiste manualmente usa el nombre del archivo, si no, la URL completa
df = pd.read_csv('asteroids_data.csv', sep=',')

# 2. Configuración para que la tabla se vea estética y completa
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)


df.head()

        id   neo_id                         name    short_name  designation                                           nasa_url  magnitude  potentially_hazardous                                close_approach_data  sentry                                            api_url  diameter_min_m  diameter_max_m  orbit_id orbit_determination_date first_observation_date last_observation_date  data_arc_days  observations_used  orbit_uncertainty  min_orbit_intersection  jupiter_tisserand      epoch  eccentricity  semi_major_axis  inclination  ascending_node_longitude  orbital_period  perihelion_distance  perihelion_argument  aphelion_distance  perihelion_time  mean_anomaly  mean_motion equinox orbit_class_type                                   orbit_class_desc                                  orbit_class_range sentry_data
0  2001620  2001620    1620 Geographos (1951 RA)    Geographos         1620  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.26                   True  [{'close_approach_date': '1901-08-23', 'close_...   False  http://api.nasa.gov/neo/rest/v1/neo/2001620?ap...     2358.060680     5272.783976       882      2026-04-19 06:20:43             1951-09-14            2026-04-16          27243               9183                  0                0.029359              5.074  2461000.5      0.335512         1.245777    13.335793                337.140792      507.877358             0.827804           277.018390           1.663750     2.461208e+06    212.920449     0.708833   J2000              APO  Near-Earth asteroid orbits which cross the Ear...  a (semi-major axis) > 1.0 AU; q (perihelion) <...         NaN
1  2001863  2001863      1863 Antinous (1948 EA)      Antinous         1863  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.35                  False  [{'close_approach_date': '1907-10-11', 'close_...   False  http://api.nasa.gov/neo/rest/v1/neo/2001863?ap...     2262.324906     5058.712276       305      2026-04-18 06:19:45             1948-03-05            2026-04-17          28532               1804                  0                0.187310              3.297  2461000.5      0.606266         2.260116    18.378651                345.551216     1241.064828             0.889883           269.074546           3.630348     2.461243e+06    289.564484     0.290073   J2000              APO  Near-Earth asteroid orbits which cross the Ear...  a (semi-major axis) > 1.0 AU; q (perihelion) <...         NaN
2  2001915  2001915  1915 Quetzalcoatl (1953 EA)  Quetzalcoatl         1915  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      18.38                  False  [{'close_approach_date': '1906-03-06', 'close_...   False  http://api.nasa.gov/neo/rest/v1/neo/2001915?ap...      560.473362     1253.256538        13      2024-03-01 04:49:33             1953-03-09            2020-10-25          24702                 55                  0                0.108832              3.122  2461000.5      0.570225         2.544841    20.399239                162.921649     1482.823498             1.093710           347.755255           3.995972     2.460911e+06     21.616448     0.242780   J2000              AMO  Near-Earth asteroid orbits similar to that of ...                 1.017 AU < q (perihelion) < 1.3 AU         NaN
3  2001917  2001917          1917 Cuyo (1968 AA)          Cuyo         1917  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      14.38                  False  [{'close_approach_date': '1926-09-28', 'close_...   False  http://api.nasa.gov/neo/rest/v1/neo/2001917?ap...     3536.347843     7907.514169       654      2026-04-20 06:20:45             1954-05-06            2026-04-19          26281               4164                  0                0.071704              3.435  2461000.5      0.505538         2.149051    23.958779                188.274896     1150.717204             1.062625           194.552572           3.235478     2.460489e+06    160.089498     0.312848   J2000              AMO  Near-Earth asteroid orbits similar to that of ...                 1.017 AU < q (perihelion) < 1.3 AU         NaN
4  2002063  2002063       2063 Bacchus (1977 HB)       Bacchus         2063  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      17.21                  False  [{'close_approach_date': '1903-03-06', 'close_...   False  http://api.nasa.gov/neo/rest/v1/neo/2002063?ap...      960.627415     2148.028201       258      2025-06-30 20:40:59             1977-04-24            2025-06-15          17584               1561                  0                0.066744              5.668  2461000.5      0.349429         1.077999     9.434707                 33.036303      408.813985             0.701315            55.350732           1.454683     2.461143e+06    234.787011     0.880596   J2000              APO  Near-Earth asteroid orbits which cross the Ear...  a (semi-major axis) > 1.0 AU; q (perihelion) <...         NaN

In [73]:
#3. Indicate the number of columns and rows. 
df.shape

(2000, 39)

In [74]:
df.columns

Index(['id', 'neo_id', 'name', 'short_name', 'designation', 'nasa_url',
       'magnitude', 'potentially_hazardous', 'close_approach_data', 'sentry',
       'api_url', 'diameter_min_m', 'diameter_max_m', 'orbit_id',
       'orbit_determination_date', 'first_observation_date',
       'last_observation_date', 'data_arc_days', 'observations_used',
       'orbit_uncertainty', 'min_orbit_intersection', 'jupiter_tisserand',
       'epoch', 'eccentricity', 'semi_major_axis', 'inclination',
       'ascending_node_longitude', 'orbital_period', 'perihelion_distance',
       'perihelion_argument', 'aphelion_distance', 'perihelion_time',
       'mean_anomaly', 'mean_motion', 'equinox', 'orbit_class_type',
       'orbit_class_desc', 'orbit_class_range', 'sentry_data'],
      dtype='str')

In [75]:
import pandas as pd
df = pd.read_csv('asteroids_data.csv', sep=',')

columnas_a_eliminar = [
    'orbit_id', 'data_arc_days', 'orbit_uncertainty', 'sentry', 'sentry_data', 'observations_used', 'jupiter_tisserand', 
    'epoch', 'eccentricity', 'semi_major_axis', 'inclination', 
    'aphelion_distance', 'perihelion_time', 'mean_anomaly', 'neo_id', 'name', 'designation',
    'mean_motion', 'equinox', 'orbit_class_type', 
    'orbit_class_desc', 'orbit_class_range', 'ascending_node_longitude', 'orbit_determination_date',
    'perihelion_distance', 'perihelion_argument', 'id', 'api_url',
    'orbit_uncertainty',
]

# 3. Usamos errors='ignore' para evitar que el código se rompa si alguna no está
df = df.drop(columns=columnas_a_eliminar, errors='ignore')

# 4. Verificamos el resultado
df.head()

     short_name                                           nasa_url  magnitude  potentially_hazardous                                close_approach_data  diameter_min_m  diameter_max_m first_observation_date last_observation_date  min_orbit_intersection  orbital_period
0    Geographos  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.26                   True  [{'close_approach_date': '1901-08-23', 'close_...     2358.060680     5272.783976             1951-09-14            2026-04-16                0.029359      507.877358
1      Antinous  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.35                  False  [{'close_approach_date': '1907-10-11', 'close_...     2262.324906     5058.712276             1948-03-05            2026-04-17                0.187310     1241.064828
2  Quetzalcoatl  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      18.38                  False  [{'close_approach_date': '1906-03-06', 'close_...      560.473362     1253.256538             1953-03-09            2020-10-25                0.108832     1482.823498
3          Cuyo  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      14.38                  False  [{'close_approach_date': '1926-09-28', 'close_...     3536.347843     7907.514169             1954-05-06            2026-04-19                0.071704     1150.717204
4       Bacchus  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      17.21                  False  [{'close_approach_date': '1903-03-06', 'close_...      960.627415     2148.028201             1977-04-24            2025-06-15                0.066744      408.813985

In [76]:
df.dropna()
df.head()

     short_name                                           nasa_url  magnitude  potentially_hazardous                                close_approach_data  diameter_min_m  diameter_max_m first_observation_date last_observation_date  min_orbit_intersection  orbital_period
0    Geographos  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.26                   True  [{'close_approach_date': '1901-08-23', 'close_...     2358.060680     5272.783976             1951-09-14            2026-04-16                0.029359      507.877358
1      Antinous  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.35                  False  [{'close_approach_date': '1907-10-11', 'close_...     2262.324906     5058.712276             1948-03-05            2026-04-17                0.187310     1241.064828
2  Quetzalcoatl  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      18.38                  False  [{'close_approach_date': '1906-03-06', 'close_...      560.473362     1253.256538             1953-03-09            2020-10-25                0.108832     1482.823498
3          Cuyo  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      14.38                  False  [{'close_approach_date': '1926-09-28', 'close_...     3536.347843     7907.514169             1954-05-06            2026-04-19                0.071704     1150.717204
4       Bacchus  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      17.21                  False  [{'close_approach_date': '1903-03-06', 'close_...      960.627415     2148.028201             1977-04-24            2025-06-15                0.066744      408.813985

In [77]:
df = df.drop_duplicates()
df.head()

     short_name                                           nasa_url  magnitude  potentially_hazardous                                close_approach_data  diameter_min_m  diameter_max_m first_observation_date last_observation_date  min_orbit_intersection  orbital_period
0    Geographos  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.26                   True  [{'close_approach_date': '1901-08-23', 'close_...     2358.060680     5272.783976             1951-09-14            2026-04-16                0.029359      507.877358
1      Antinous  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.35                  False  [{'close_approach_date': '1907-10-11', 'close_...     2262.324906     5058.712276             1948-03-05            2026-04-17                0.187310     1241.064828
2  Quetzalcoatl  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      18.38                  False  [{'close_approach_date': '1906-03-06', 'close_...      560.473362     1253.256538             1953-03-09            2020-10-25                0.108832     1482.823498
3          Cuyo  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      14.38                  False  [{'close_approach_date': '1926-09-28', 'close_...     3536.347843     7907.514169             1954-05-06            2026-04-19                0.071704     1150.717204
4       Bacchus  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      17.21                  False  [{'close_approach_date': '1903-03-06', 'close_...      960.627415     2148.028201             1977-04-24            2025-06-15                0.066744      408.813985

In [78]:
df.columns

Index(['short_name', 'nasa_url', 'magnitude', 'potentially_hazardous',
       'close_approach_data', 'diameter_min_m', 'diameter_max_m',
       'first_observation_date', 'last_observation_date',
       'min_orbit_intersection', 'orbital_period'],
      dtype='str')

In [79]:
# interesante para el analisis, crear tabla
print(df['close_approach_data'].iloc[0])

[{'close_approach_date': '1901-08-23', 'close_approach_date_full': '1901-Aug-23 17:36', 'epoch_date_close_approach': -2157171840000, 'relative_velocity': {'kilometers_per_second': '11.7628117092', 'kilometers_per_hour': '42346.1221532154', 'miles_per_hour': '26312.2335123688'}, 'miss_distance': {'astronomical': '0.0338992178', 'lunar': '13.1867957242', 'kilometers': '5071250.777546086', 'miles': '3151129.1133685468'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1915-03-14', 'close_approach_date_full': '1915-Mar-14 16:15', 'epoch_date_close_approach': -1729410300000, 'relative_velocity': {'kilometers_per_second': '12.1053300316', 'kilometers_per_hour': '43579.1881138885', 'miles_per_hour': '27078.4127477659'}, 'miss_distance': {'astronomical': '0.081599517', 'lunar': '31.742212113', 'kilometers': '12207113.93622879', 'miles': '7585148.871945702'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1926-08-21', 'close_approach_date_full': '1926-Aug-21 06:24', 'epoch_date_close_approach': -1368466560000, 'relative_velocity': {'kilometers_per_second': '10.5595594552', 'kilometers_per_hour': '38014.4140388284', 'miles_per_hour': '23620.6785454042'}, 'miss_distance': {'astronomical': '0.066484503', 'lunar': '25.862471667', 'kilometers': '9945940.03680861', 'miles': '6180120.562874418'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1940-03-09', 'close_approach_date_full': '1940-Mar-09 21:19', 'epoch_date_close_approach': -940819260000, 'relative_velocity': {'kilometers_per_second': '14.994052549', 'kilometers_per_hour': '53978.5891764079', 'miles_per_hour': '33540.196146863'}, 'miss_distance': {'astronomical': '0.1470295814', 'lunar': '57.1945071646', 'kilometers': '21995312.204431618', 'miles': '13667253.2448796084'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1944-09-02', 'close_approach_date_full': '1944-Sep-02 03:37', 'epoch_date_close_approach': -799359780000, 'relative_velocity': {'kilometers_per_second': '16.7374296016', 'kilometers_per_hour': '60254.7465658234', 'miles_per_hour': '37439.9562758584'}, 'miss_distance': {'astronomical': '0.19163773', 'lunar': '74.54707697', 'kilometers': '28668596.2196351', 'miles': '17813839.65216038'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1951-08-08', 'close_approach_date_full': '1951-Aug-08 15:38', 'epoch_date_close_approach': -580638120000, 'relative_velocity': {'kilometers_per_second': '7.9958930562', 'kilometers_per_hour': '28785.2150023975', 'miles_per_hour': '17886.0131774619'}, 'miss_distance': {'astronomical': '0.1936526689', 'lunar': '75.3308882021', 'kilometers': '28970026.787255243', 'miles': '18001139.9216506334'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1958-03-18', 'close_approach_date_full': '1958-Mar-18 04:43', 'epoch_date_close_approach': -372107820000, 'relative_velocity': {'kilometers_per_second': '9.0553681421', 'kilometers_per_hour': '32599.3253116115', 'miles_per_hour': '20255.9529970955'}, 'miss_distance': {'astronomical': '0.1515042093', 'lunar': '58.9351374177', 'kilometers': '22664707.007314191', 'miles': '14083195.8878741958'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1969-08-27', 'close_approach_date_full': '1969-Aug-27 00:06', 'epoch_date_close_approach': -10972440000, 'relative_velocity': {'kilometers_per_second': '13.176537182', 'kilometers_per_hour': '47435.5338552936', 'miles_per_hour': '29474.596022474'}, 'miss_distance': {'astronomical': '0.0606033695', 'lunar': '23.5747107355', 'kilometers': '9066134.992022965', 'miles': '5633435.058188317'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1983-03-16', 'close_approach_date_full': '1983-Mar-16 10:22', 'epoch_date_close_approach': 416658120000, 'relative_velocity': {'kilometers_per_second': '11.0596560379', 'kilometers_per_hour': '39814.7617363529', 'miles_per_hour': '24739.3445911244'}, 'miss_distance': {'astronomical': '0.0894588501', 'lunar': '34.7994926889', 'kilometers': '13382853.427609287', 'miles': '8315719.5148786806'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '1994-08-25', 'close_approach_date_full': '1994-Aug-25 10:10', 'epoch_date_close_approach': 777809400000, 'relative_velocity': {'kilometers_per_second': '12.2172333919', 'kilometers_per_hour': '43982.0402107442', 'miles_per_hour': '27328.7293742816'}, 'miss_distance': {'astronomical': '0.0333047312', 'lunar': '12.9555404368', 'kilometers': '4982316.848442544', 'miles': '3095868.1323093472'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2008-03-17', 'close_approach_date_full': '2008-Mar-17 11:41', 'epoch_date_close_approach': 1205754060000, 'relative_velocity': {'kilometers_per_second': '9.7438577103', 'kilometers_per_hour': '35077.8877572262', 'miles_per_hour': '21796.0353122609'}, 'miss_distance': {'astronomical': '0.1251027022', 'lunar': '48.6649511558', 'kilometers': '18715097.780364314', 'miles': '11629022.5157789732'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2019-08-31', 'close_approach_date_full': '2019-Aug-31 17:20', 'epoch_date_close_approach': 1567272000000, 'relative_velocity': {'kilometers_per_second': '15.2835382875', 'kilometers_per_hour': '55020.7378349953', 'miles_per_hour': '34187.7467953058'}, 'miss_distance': {'astronomical': '0.137257621', 'lunar': '53.393214569', 'kilometers': '20533447.74286727', 'miles': '12758892.789697526'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2026-08-12', 'close_approach_date_full': '2026-Aug-12 08:35', 'epoch_date_close_approach': 1786523700000, 'relative_velocity': {'kilometers_per_second': '8.3615352841', 'kilometers_per_hour': '30101.5270226935', 'miles_per_hour': '18703.918276962'}, 'miss_distance': {'astronomical': '0.1704372825', 'lunar': '66.3001028925', 'kilometers': '25497054.430588275', 'miles': '15843134.967237195'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2040-03-12', 'close_approach_date_full': '2040-Mar-12 10:58', 'epoch_date_close_approach': 2215162680000, 'relative_velocity': {'kilometers_per_second': '13.743009251', 'kilometers_per_hour': '49474.8333036868', 'miles_per_hour': '30741.7373936158'}, 'miss_distance': {'astronomical': '0.113638662', 'lunar': '44.205439518', 'kilometers': '17000101.78484994', 'miles': '10563373.418971572'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2051-08-23', 'close_approach_date_full': '2051-Aug-23 03:35', 'epoch_date_close_approach': 2576374500000, 'relative_velocity': {'kilometers_per_second': '11.0130376757', 'kilometers_per_hour': '39646.9356325762', 'miles_per_hour': '24635.0639768082'}, 'miss_distance': {'astronomical': '0.0478817154', 'lunar': '18.6259872906', 'kilometers': '7163002.635786198', 'miles': '4450883.4476696124'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2065-03-13', 'close_approach_date_full': '2065-Mar-13 19:56', 'epoch_date_close_approach': 3004199760000, 'relative_velocity': {'kilometers_per_second': '12.9517021223', 'kilometers_per_hour': '46626.1276403596', 'miles_per_hour': '28971.6624774223'}, 'miss_distance': {'astronomical': '0.0965980597', 'lunar': '37.5766452233', 'kilometers': '14450863.977252839', 'miles': '8979350.4974496182'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2076-08-20', 'close_approach_date_full': '2076-Aug-20 09:35', 'epoch_date_close_approach': 3365141700000, 'relative_velocity': {'kilometers_per_second': '10.2248347985', 'kilometers_per_hour': '36809.4052745978', 'miles_per_hour': '22871.9329607633'}, 'miss_distance': {'astronomical': '0.0783701682', 'lunar': '30.4859954298', 'kilometers': '11724010.234261734', 'miles': '7284962.1513865692'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2090-03-11', 'close_approach_date_full': '2090-Mar-11 06:39', 'epoch_date_close_approach': 3792897540000, 'relative_velocity': {'kilometers_per_second': '15.0059356206', 'kilometers_per_hour': '54021.368234228', 'miles_per_hour': '33566.7773897624'}, 'miss_distance': {'astronomical': '0.1508072994', 'lunar': '58.6640394666', 'kilometers': '22560450.770692278', 'miles': '14018414.0664103164'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2094-09-03', 'close_approach_date_full': '2094-Sep-03 10:34', 'epoch_date_close_approach': 3934348440000, 'relative_velocity': {'kilometers_per_second': '16.6942590555', 'kilometers_per_hour': '60099.3325997928', 'miles_per_hour': '37343.3880812435'}, 'miss_distance': {'astronomical': '0.1900233795', 'lunar': '73.9190946255', 'kilometers': '28427092.823401665', 'miles': '17663776.400266377'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2101-08-07', 'close_approach_date_full': '2101-Aug-07 02:26', 'epoch_date_close_approach': 4152824760000, 'relative_velocity': {'kilometers_per_second': '8.0119290343', 'kilometers_per_hour': '28842.9445234844', 'miles_per_hour': '17921.8840568284'}, 'miss_distance': {'astronomical': '0.1980370795', 'lunar': '77.0364239255', 'kilometers': '29625925.274220665', 'miles': '18408696.342808577'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2108-03-18', 'close_approach_date_full': '2108-Mar-18 23:57', 'epoch_date_close_approach': 4361558220000, 'relative_velocity': {'kilometers_per_second': '9.3905190283', 'kilometers_per_hour': '33805.868501789', 'miles_per_hour': '21005.6520143477'}, 'miss_distance': {'astronomical': '0.139565367', 'lunar': '54.290927763', 'kilometers': '20878681.62896829', 'miles': '12973411.179170802'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2119-08-27', 'close_approach_date_full': '2119-Aug-27 16:11', 'epoch_date_close_approach': 4722595860000, 'relative_velocity': {'kilometers_per_second': '12.3889920066', 'kilometers_per_hour': '44600.3712238248', 'miles_per_hour': '27712.9362196038'}, 'miss_distance': {'astronomical': '0.0336165502', 'lunar': '13.0768380278', 'kilometers': '5028964.306668074', 'miles': '3124853.5187804612'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2133-03-18', 'close_approach_date_full': '2133-Mar-18 05:51', 'epoch_date_close_approach': 5150411460000, 'relative_velocity': {'kilometers_per_second': '10.6944232848', 'kilometers_per_hour': '38499.9238252634', 'miles_per_hour': '23922.3554457588'}, 'miss_distance': {'astronomical': '0.1005941724', 'lunar': '39.1311330636', 'kilometers': '15048673.925452788', 'miles': '9350812.3743449544'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2144-08-29', 'close_approach_date_full': '2144-Aug-29 08:08', 'epoch_date_close_approach': 5511744480000, 'relative_velocity': {'kilometers_per_second': '13.5183022022', 'kilometers_per_hour': '48665.8879278023', 'miles_per_hour': '30239.090196028'}, 'miss_distance': {'astronomical': '0.0705258076', 'lunar': '27.4345391564', 'kilometers': '10550510.596989812', 'miles': '6555783.2892589256'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2158-03-20', 'close_approach_date_full': '2158-Mar-20 02:29', 'epoch_date_close_approach': 5939490540000, 'relative_velocity': {'kilometers_per_second': '8.6455572576', 'kilometers_per_hour': '31124.0061272188', 'miles_per_hour': '19339.2470294377'}, 'miss_distance': {'astronomical': '0.1750878029', 'lunar': '68.1091553281', 'kilometers': '26192762.376819823', 'miles': '16275427.8393386374'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2165-03-11', 'close_approach_date_full': '2165-Mar-11 12:24', 'epoch_date_close_approach': 6159673440000, 'relative_velocity': {'kilometers_per_second': '15.883692413', 'kilometers_per_hour': '57181.2926867694', 'miles_per_hour': '35530.2315586207'}, 'miss_distance': {'astronomical': '0.180381539', 'lunar': '70.168418671', 'kilometers': '26984694.02172193', 'miles': '16767511.345265434'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2176-08-20', 'close_approach_date_full': '2176-Aug-20 12:13', 'epoch_date_close_approach': 6520824780000, 'relative_velocity': {'kilometers_per_second': '9.8725060774', 'kilometers_per_hour': '35541.0218786767', 'miles_per_hour': '22083.8088445589'}, 'miss_distance': {'astronomical': '0.0936338697', 'lunar': '36.4235753133', 'kilometers': '14007427.466977539', 'miles': '8703811.8268624782'}, 'orbiting_body': 'Earth'}, {'close_approach_date': '2190-03-16', 'close_approach_date_full': '2190-Mar-16 04:16', 'epoch_date_close_approach': 6948994560000, 'relative_velocity': {'kilometers_per_second': '12.7193170135', 'kilometers_per_hour': '45789.5412487231', 'miles_per_hour': '28451.8402275747'}, 'miss_distance': {'astronomical': '0.0965581492', 'lunar': '37.5611200388', 'kilometers': '14444893.451462204', 'miles': '8975640.5847542552'}, 'orbiting_body': 'Earth'}]

In [80]:
df = df.rename(columns={'short_name': 'name'})

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    167 non-null    str
 1   nasa_url                2000 non-null   str
 2   magnitude               2000 non-null   float64
 3   potentially_hazardous   2000 non-null   bool
 4   close_approach_data     2000 non-null   str
 5   diameter_min_m          2000 non-null   float64
 6   diameter_max_m          2000 non-null   float64
 7   first_observation_date  2000 non-null   str
 8   last_observation_date   2000 non-null   str
 9   min_orbit_intersection  2000 non-null   float64
 10  orbital_period          2000 non-null   float64
dtypes: bool(1), float64(5), str(5)
memory usage: 158.3 KB

In [82]:
# Count the number of null values in each column
df.isna().sum()

name                      1833
nasa_url                     0
magnitude                    0
potentially_hazardous        0
close_approach_data          0
diameter_min_m               0
diameter_max_m               0
first_observation_date       0
last_observation_date        0
min_orbit_intersection       0
orbital_period               0
dtype: int64

Eliminamos los asteroides que no tienen nombre vernaculares, porque a los gordos, en general,  si se le atribue uno y son los que nos interesan a nostros. Además son los que se van a quedar en la mente del público

In [83]:
df = df.dropna(subset=['name'])
print(f'Shape final: {df.shape}')

Shape final: (167, 11)

In [89]:
import pandas as pd

try:
    # 1. Cargar el dataset original
    df = pd.read_csv('asteroids_data.csv', sep=',')

    # 2. Lista de columnas a eliminar (incluyendo las técnicas y las que causaban error)
    columnas_a_eliminar = [
        'orbit_id', 'data_arc_days', 'orbit_uncertainty', 'sentry', 'sentry_data', 
        'observations_used', 'jupiter_tisserand', 'epoch', 'eccentricity', 
        'semi_major_axis', 'inclination', 'aphelion_distance', 'perihelion_time', 
        'mean_anomaly', 'neo_id', 'name', 'designation', 'mean_motion', 'equinox', 
        'orbit_class_type', 'orbit_class_desc', 'orbit_class_range', 
        'ascending_node_longitude', 'orbit_determination_date', 
        'perihelion_distance', 'perihelion_argument', 'id', 'api_url'
    ]

    # 3. Aplicar limpieza de columnas y duplicados
    df = df.drop(columns=columnas_a_eliminar, errors='ignore')
    df = df.drop_duplicates()

    # 4. Renombrar short_name a name y limpiar nulos en el nombre
    if 'short_name' in df.columns:
        df = df.rename(columns={'short_name': 'name'})
    
    df = df.dropna(subset=['name'])

    # 5. Gestión de velocidad: Conversión a km/h y eliminación de nulos
    if 'velocidad_km_s' in df.columns:
        # Eliminamos filas donde la velocidad sea nula antes de calcular
        df = df.dropna(subset=['velocidad_km_s'])
        # Creamos la columna en km/h
        df['velocidad_km_h'] = df['velocidad_km_s'] * 3600

    # 6. Guardar el archivo definitivo
    df.to_csv('dataset_asteroides_final.csv', index=False)

    print(f"✅ Archivo 'dataset_asteroides_final.csv' creado con éxito.")
    print(f"📏 Shape final: {df.shape}")
    print(f"📊 Columnas resultantes: {list(df.columns)}")

except Exception as e:
    print(f"❌ Error al procesar el dataset: {e}")

✅ Archivo 'dataset_asteroides_final.csv' creado con éxito.
📏 Shape final: (167, 11)
📊 Columnas resultantes: ['name', 'nasa_url', 'magnitude', 'potentially_hazardous', 'close_approach_data', 'diameter_min_m', 'diameter_max_m', 'first_observation_date', 'last_observation_date', 'min_orbit_intersection', 'orbital_period']

In [91]:
df.head()

           name                                           nasa_url  magnitude  potentially_hazardous                                close_approach_data  diameter_min_m  diameter_max_m first_observation_date last_observation_date  min_orbit_intersection  orbital_period
0    Geographos  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.26                   True  [{'close_approach_date': '1901-08-23', 'close_...     2358.060680     5272.783976             1951-09-14            2026-04-16                0.029359      507.877358
1      Antinous  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      15.35                  False  [{'close_approach_date': '1907-10-11', 'close_...     2262.324906     5058.712276             1948-03-05            2026-04-17                0.187310     1241.064828
2  Quetzalcoatl  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      18.38                  False  [{'close_approach_date': '1906-03-06', 'close_...      560.473362     1253.256538             1953-03-09            2020-10-25                0.108832     1482.823498
3          Cuyo  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      14.38                  False  [{'close_approach_date': '1926-09-28', 'close_...     3536.347843     7907.514169             1954-05-06            2026-04-19                0.071704     1150.717204
4       Bacchus  https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...      17.21                  False  [{'close_approach_date': '1903-03-06', 'close_...      960.627415     2148.028201             1977-04-24            2025-06-15                0.066744      408.813985

In [97]:
import pandas as pd
import ast
import mysql.connector

try:
    # 1. Cargar el dataset original
    df = pd.read_csv('asteroids_data.csv', sep=',')

    # --- EXTRACCIÓN DE DATOS (Basado en image_865674.png) ---
    def extract_nasa_data(row):
        try:
            # Convertimos el string de la celda en una lista real de Python
            data_list = ast.literal_eval(row)
            if data_list and len(data_list) > 0:
                first_approach = data_list[0]
                date = first_approach.get('close_approach_date')
                # Extraemos velocidad en km/s para el cálculo
                vel_s = first_approach.get('relative_velocity', {}).get('kilometers_per_second', 0)
                return pd.Series([date, float(vel_s)])
        except:
            pass
        return pd.Series([None, 0.0])

    print("🔍 Extracting date and velocity from nested data...")
    df[['approach_date', 'velocity_km_s']] = df['close_approach_data'].apply(extract_nasa_data)

    # 2. Renombrar short_name a 'name' (según tus cambios previos)
    if 'short_name' in df.columns:
        df = df.rename(columns={'short_name': 'name'})

    # 3. Cálculo de velocidad en km/h y limpieza
    df['velocity_km_h'] = df['velocity_km_s'] * 3600
    
    # Seleccionamos solo las columnas que pediste en inglés
    df_final = df[['name', 'approach_date', 'velocity_km_h']].copy()
    
    # Limpieza: eliminamos filas con nulos y ordenamos de forma descendente por velocidad
    df_final = df_final.dropna().sort_values(by='velocity_km_h', ascending=False)

    # 4. Guardar el CSV limpio (English version)
    df_final.to_csv('dataset_asteroides_final.csv', index=False)
    print("✅ 'dataset_asteroides_final.csv' created successfully.")

    # --- MYSQL INTEGRATION ---
    config = {
        'user': 'root',
        'password': 'kP92mXv7R4wQ', 
        'host': '127.0.0.1',
        'database': 'asteroides_listo_para_sql'
    }

    conn = mysql.connector.connect(**config)
    cursor = conn.cursor()

    # Recreamos la tabla con los nombres en inglés
    cursor.execute("DROP TABLE IF EXISTS `asteroides_ranking`")
    cursor.execute("""
        CREATE TABLE `asteroides_ranking` (
            `name` VARCHAR(250) PRIMARY KEY,
            `approach_date` DATE,
            `velocity_km_h` FLOAT
        )
    """)

    # Inserción masiva de los datos ya ordenados
    sql_insert = "INSERT INTO `asteroides_ranking` (name, approach_date, velocity_km_h) VALUES (%s, %s, %s)"
    
    # Convertimos el DataFrame a lista de tuplas para la carga
    data_to_insert = [tuple(x) for x in df_final.values]
    cursor.executemany(sql_insert, data_to_insert)
    
    conn.commit()
    print(f"✅ MySQL table updated: {cursor.rowcount} rows inserted in descending order.")

    # 5. Consulta para verificar el Top 10 para tu video
    print("\n🎬 TOP 10 FOR THE VIDEO:")
    print("-" * 50)
    for row in data_to_insert[:10]:
        print(f"Asteroid: {row[0]:<20} | Speed: {row[2]:>10.2f} km/h | Date: {row[1]}")

except Exception as e:
    print(f"❌ Error: {e}")
finally:
    if 'conn' in locals() and conn.is_connected():
        cursor.close()
        conn.close()

🔍 Extracting date and velocity from nested data...
✅ 'dataset_asteroides_final.csv' created successfully.
❌ Error: Failed executing the operation; Not all parameters were used in the SQL statement

In [ ]:
name	nasa_url	magnitude	potentially_hazardous	diameter_min_m	diameter_max_m	first_observation_date	last_observation_date	min_orbit_intersection	orbital_period	fecha_acercamiento	velocidad_km_s	velocidad_km_h